<?xml version="1.0" encoding="utf-8"?><Database Name="Expert" Class="ExpertHelperDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Database\Expert.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="ExpertHelper.Properties.Settings" SettingsPropertyName="ExpertConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Kryterium" Member="Kryteriums">
    <Type Name="Kryterium">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Rodzica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Data_utworzenia" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Liczba_Podkryteriow" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Kryterium_Warianty_Celu" Member="Warianty_Celus" ThisKey="ID" OtherKey="ID_Celu" Type="Warianty_Celu" />
      <Association Name="Kryterium_Waga" Member="Wagas" ThisKey="ID" OtherKey="Kryterium1" Type="Waga" />
      <Association Name="Kryterium_Waga1" Member="Wagas1" ThisKey="ID" OtherKey="Kryterium2" Type="Waga" />
    </Type>
  </Table>
  <Table Name="dbo.Warianty_Celu" Member="Warianty_Celus">
    <Type Name="Warianty_Celu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Celu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_Wariantu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Kryterium_Warianty_Celu" Member="Kryterium" ThisKey="ID_Celu" OtherKey="ID" Type="Kryterium" IsForeignKey="true" />
      <Association Name="Wariant_Warianty_Celu" Member="Wariant" ThisKey="ID_Wariantu" OtherKey="ID_Wariantu" Type="Wariant" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Waga" Member="Wagas">
    <Type Name="Waga">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Kryterium1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Kryterium2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Waga" Member="Waga1" Type="System.Decimal" DbType="Decimal(18,18) NOT NULL" CanBeNull="false" />
      <Association Name="Kryterium_Waga" Member="Kryterium" ThisKey="Kryterium1" OtherKey="ID" Type="Kryterium" IsForeignKey="true" />
      <Association Name="Kryterium_Waga1" Member="Kryterium3" ThisKey="Kryterium2" OtherKey="ID" Type="Kryterium" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Wariant" Member="Wariants">
    <Type Name="Wariant">
      <Column Name="ID_Wariantu" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Opis" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Wariant_Warianty_Celu" Member="Warianty_Celus" ThisKey="ID_Wariantu" OtherKey="ID_Wariantu" Type="Warianty_Celu" />
    </Type>
  </Table>
</Database>